name: Auto-Compile
on: 
  release:
    types: [published]
jobs:
  compile:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Automatically build action
        uses: JasonEtco/github-action-auto-compile-node@custom-entrypoint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
