name: Auto-Compile
on: release
jobs:
  compile:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Automatically build action
        uses: mheap/github-action-auto-compile-node@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
